### ISSUE TITLE
register-package not working

### ISSUE THREAD

**Issue by mjanjic01** [fuse-box/fuse-box-examples#18]
Trying to run the register-package example gives this error:

```
TypeError: Cannot read property 'isAsyncProp' of undefined
    at isAsyncProp (/Users/mjanjic/Projects/fuse-box-examples/node_modules/fuse-box/dist/commonjs/analysis/acorn-ext/obj-rest-spread.js:87:23)
    at Parser.parseObj (/Users/mjanjic/Projects/fuse-box-examples/node_modules/fuse-box/dist/commonjs/analysis/acorn-ext/obj-rest-spread.js:49:17)
    at Parser.parseObj (/Users/mjanjic/Projects/fuse-box-examples/node_modules/fuse-box/dist/commonjs/analysis/acorn-ext/obj-rest-spread.js:3:24)
    at Parser.pp$3.parseExprAtom (/Users/mjanjic/Projects/fuse-box-examples/node_modules/acorn/dist/acorn.js:1994:17)
    at Parser.parseExprAtom (/Users/mjanjic/Projects/fuse-box-examples/node_modules/acorn-jsx/inject.js:383:24)
    at Parser.pp$3.parseExprSubscripts (/Users/mjanjic/Projects/fuse-box-examples/node_modules/acorn/dist/acorn.js:1872:19)
    at Parser.pp$3.parseMaybeUnary (/Users/mjanjic/Projects/fuse-box-examples/node_modules/acorn/dist/acorn.js:1849:17)
    at Parser.pp$3.parseExprOps (/Users/mjanjic/Projects/fuse-box-examples/node_modules/acorn/dist/acorn.js:1791:19)
    at Parser.pp$3.parseMaybeConditional (/Users/mjanjic/Projects/fuse-box-examples/node_modules/acorn/dist/acorn.js:1774:19)
    at Parser.pp$3.parseMaybeAssign (/Users/mjanjic/Projects/fuse-box-examples/node_modules/acorn/dist/acorn.js:1750:19)
```
I am also not managing to register the package in my own examples without TypeScript (the package is not contained in the bundle)

macOS v10.13.1 
Node v8.9.0
NPM v5.5.1

**Comment by mjanjic01** [comment]
Updated TypeScript, seems to work now.
